title: S!THás' Stuffs
author:
  date: 2020
  name: Gábor Szitás
  email: gabor.szitas.work@gmail.com
minima:
  date_format: '%Y. %b %d.'
  social_links:
    linkedin: gábor-szitás-6b6b1957
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
google_analytics: UA-34910729-2
