title: S!THás' Stuffs
description: Personal blog including cooking, LEGO, IT, renovation, parenting and a lot of other topics
url: https://szitasg.github.io
baseurl:
site-twitter:

# Author settings
author: Gábor Szitás
img: me.jpg
about-author:
social-twitter:
social-facebook:
social-github: szitasg
social-linkedin: gábor-szitás-6b6b1957
social-email: gabor.szitas.work@gmail.com

# Tracker
analytics: UA-34910729-2

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
paginate: 8
paginate_path: /page/:num

# szitasg feature
feature:
  date_format: '%Y. %b %d.'
